# Generated by Django 3.2.9 on 2022-03-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0045_alter_mover_quote_request_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movers_Email_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mover', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.mover')),
                ('quote_request', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.quote_request')),
            ],
        ),
    ]
