# Generated by Django 3.2.9 on 2022-01-25 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='', max_length=30)),
                ('company_name', models.CharField(max_length=300)),
                ('company_email', models.EmailField(max_length=254)),
                ('Adresse', models.CharField(default='', max_length=300)),
                ('City', models.CharField(default='', max_length=300)),
                ('country', models.CharField(default='', max_length=300)),
                ('company_phone_number', models.CharField(max_length=50)),
                ('Postal_Code', models.IntegerField(default=0)),
                ('employee_number', models.IntegerField(default=0)),
                ('TVA_number', models.CharField(default='', max_length=30)),
                ('company_description', models.TextField(default='')),
                ('website', models.CharField(default='', max_length=300)),
                ('company_statut', models.CharField(default='', max_length=300)),
                ('facebook_link', models.CharField(default='', max_length=500)),
                ('instagram_link', models.CharField(default='', max_length=500)),
                ('twitter_link', models.CharField(default='', max_length=500)),
                ('linkedin_link', models.CharField(default='', max_length=500)),
                ('logo', models.ImageField(blank=True, default='', upload_to='base_app/images/')),
                ('validated', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moving_Type1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Moving_Type2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RegionOrProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Mover_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=300)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.country')),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.mover')),
                ('region', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.regionorprovince')),
            ],
        ),
        migrations.CreateModel(
            name='Mover_Moving_Type2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moving_type2_name', models.CharField(default='', max_length=300)),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.mover')),
            ],
        ),
        migrations.CreateModel(
            name='Mover_Moving_Type1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moving_type1_name', models.CharField(default='', max_length=300)),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.mover')),
            ],
        ),
        migrations.CreateModel(
            name='Mover_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='base_app/images/')),
                ('mover', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.mover')),
            ],
        ),
        migrations.CreateModel(
            name='Mover_Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=300)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.country')),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.mover')),
            ],
        ),
    ]
