# Generated by Django 3.2.9 on 2022-02-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=30)),
                ('Postal_Code_Departure', models.IntegerField()),
                ('City_Departure', models.CharField(max_length=300)),
                ('Adresse_Departure', models.CharField(max_length=300)),
                ('Residence_Number_or_Name_Departure', models.CharField(max_length=300)),
                ('Postal_Code_Arrival', models.IntegerField()),
                ('City_Arrival', models.CharField(max_length=300)),
                ('Adresse_Arrival', models.CharField(max_length=300)),
                ('Residence_Number_or_Name_Arrival', models.CharField(max_length=300)),
                ('Residence_Departure', models.CharField(max_length=300)),
                ('Residence_Arrival', models.CharField(max_length=300)),
                ('Number_Room_Departure', models.IntegerField()),
                ('Additional_informations', models.CharField(max_length=300)),
                ('moving_date1', models.DateTimeField()),
                ('moving_date2', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('moving_description', models.TextField()),
                ('moving_type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.moving_type1')),
                ('moving_type2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.moving_type2')),
            ],
        ),
    ]
