# Generated by Django 3.2.9 on 2022-02-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20220208_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request',
            name='user',
        ),
        migrations.AddField(
            model_name='quote_request',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.country'),
        ),
    ]
