# Generated by Django 3.2.9 on 2022-02-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20220208_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_request',
            name='furniture_assembly_disassembly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote_request',
            name='furniture_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote_request',
            name='packaging_materials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote_request',
            name='packing_service',
            field=models.BooleanField(default=False),
        ),
    ]
