# Generated by Django 3.2.9 on 2022-02-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_auto_20220208_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request',
            name='social_reason',
        ),
    ]
