# Generated by Django 3.2.9 on 2022-02-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_remove_quote_request_social_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request',
            name='moving_description',
        ),
    ]
