# Generated by Django 3.2.9 on 2022-02-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_remove_quote_request_moving_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote_Request',
        ),
    ]
