# Generated by Django 3.2.9 on 2022-02-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_delete_quote_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=30)),
                ('City_Departure', models.CharField(max_length=300)),
                ('Postal_Code_Departure', models.IntegerField()),
                ('Adresse_Departure', models.CharField(max_length=300)),
                ('Residence_Number_or_Name_Departure', models.CharField(max_length=300)),
                ('City_Arrival', models.CharField(max_length=300)),
                ('Adresse_Arrival', models.CharField(max_length=300)),
                ('Residence_Number_or_Name_Arrival', models.CharField(max_length=300)),
                ('Postal_Code_Arrival', models.IntegerField()),
                ('Residence_Departure', models.CharField(max_length=300)),
                ('Number_Room_Departure', models.IntegerField()),
                ('Residence_Arrival', models.CharField(max_length=300)),
                ('packing_service', models.BooleanField(default=False)),
                ('packaging_materials', models.BooleanField(default=False)),
                ('furniture_assembly_disassembly', models.BooleanField(default=False)),
                ('furniture_storage', models.BooleanField(default=False)),
                ('firstname', models.CharField(default='', max_length=300)),
                ('lastname', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=30)),
                ('Additional_informations', models.CharField(max_length=300)),
                ('moving_date', models.DateTimeField()),
                ('moving_date1', models.DateTimeField()),
                ('moving_date2', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.country')),
                ('moving_type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.moving_type1')),
                ('moving_type2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.moving_type2')),
            ],
        ),
    ]
