# Generated by Django 3.2.9 on 2022-02-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_quote_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mover',
            name='company_email',
        ),
    ]
