# Generated by Django 3.2.9 on 2022-02-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_remove_mover_company_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mover_Quote_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.mover')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.quote_request')),
            ],
        ),
    ]
