# Generated by Django 3.2.9 on 2022-02-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_auto_20220214_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request',
            name='Country_Departure',
        ),
    ]
