# Generated by Django 3.2.9 on 2022-02-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_remove_quote_request_country_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover_country',
            name='arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mover_country',
            name='departure',
            field=models.BooleanField(default=False),
        ),
    ]
