# Generated by Django 3.2.9 on 2022-02-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_auto_20220215_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover',
            name='number_max_quote_request',
            field=models.IntegerField(default=0),
        ),
    ]
