# Generated by Django 3.2.9 on 2022-02-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_mover_number_max_quote_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_Mover_Quote_Request_Per_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_quote_received_the_same_day', models.IntegerField()),
                ('reception_date_quote_request', models.DateTimeField(auto_now_add=True)),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.mover')),
            ],
        ),
    ]
