# Generated by Django 3.2.9 on 2022-02-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_mover_number_max_quote_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mover',
            name='country',
        ),
    ]
