# Generated by Django 3.2.9 on 2022-02-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_number_mover_quote_request_perday'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.country'),
        ),
    ]
