# Generated by Django 3.2.9 on 2022-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_mover_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_request',
            name='distributed',
            field=models.BooleanField(default=False),
        ),
    ]
