# Generated by Django 3.2.9 on 2022-02-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0021_alter_mover_number_max_quote_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mover',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='user/images/profil_image/'),
        ),
    ]
