# Generated by Django 3.2.9 on 2022-02-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_alter_mover_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mover',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='mover',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='mover',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='mover',
            name='twitter_link',
        ),
    ]
