# Generated by Django 3.2.9 on 2022-02-23 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0023_auto_20220223_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_Request_Waiting_Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.quote_request')),
            ],
        ),
    ]
