# Generated by Django 3.2.9 on 2022-02-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0024_quote_request_waiting_liste'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover',
            name='moving_type1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.moving_type1'),
        ),
    ]
