# Generated by Django 3.2.9 on 2022-02-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0025_mover_moving_type1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mover_Moving_Type1',
        ),
    ]
