# Generated by Django 3.2.9 on 2022-02-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0026_delete_mover_moving_type1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_Distribution_Quote_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_distribution', models.IntegerField()),
                ('number_max_distribution', models.IntegerField(default=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.quote_request')),
            ],
        ),
    ]
