# Generated by Django 3.2.9 on 2022-02-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0028_auto_20220227_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_request_rejected',
            name='mover',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.mover'),
        ),
    ]
