# Generated by Django 3.2.9 on 2022-02-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0029_quote_request_rejected_mover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request_rejected',
            name='mover',
        ),
        migrations.RemoveField(
            model_name='quote_request_rejected',
            name='quote_request',
        ),
        migrations.AddField(
            model_name='quote_request_rejected',
            name='mover_quote_request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.mover_quote_request'),
        ),
    ]
