# Generated by Django 3.2.9 on 2022-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0030_auto_20220227_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover_quote_request',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
