# Generated by Django 3.2.9 on 2022-03-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0031_mover_quote_request_rejected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='quote_request_waiting_liste',
            name='quote_request',
        ),
        migrations.RemoveField(
            model_name='regionorprovince',
            name='country',
        ),
        migrations.DeleteModel(
            name='Mover_Region',
        ),
        migrations.DeleteModel(
            name='Quote_Request_Waiting_Liste',
        ),
        migrations.DeleteModel(
            name='RegionOrProvince',
        ),
    ]
