# Generated by Django 3.2.9 on 2022-03-02 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0032_auto_20220302_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_stars', models.IntegerField()),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mover_quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.mover_quote_request')),
            ],
        ),
    ]
