# Generated by Django 3.2.9 on 2022-03-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0033_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='number_stars',
        ),
        migrations.AddField(
            model_name='review',
            name='organisation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='reliability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
