# Generated by Django 3.2.9 on 2022-03-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0034_auto_20220302_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mover',
            name='number_max_quote_request',
            field=models.IntegerField(default=0),
        ),
    ]
