# Generated by Django 3.2.9 on 2022-03-08 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0037_auto_20220308_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients_email',
            name='mover_quote_request',
        ),
        migrations.RemoveField(
            model_name='movers_email',
            name='mover_quote_request',
        ),
        migrations.AddField(
            model_name='clients_email',
            name='quote_request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.quote_request'),
        ),
        migrations.AddField(
            model_name='movers_email',
            name='quote_request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.quote_request'),
        ),
    ]
