# Generated by Django 3.2.9 on 2022-03-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0038_auto_20220308_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='movers_email',
            name='mover',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.mover'),
        ),
    ]
