# Generated by Django 3.2.9 on 2022-03-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0042_auto_20220309_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients_Email',
        ),
    ]
