# Generated by Django 3.2.9 on 2022-03-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0044_mover_quote_request_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mover_quote_request',
            name='paid',
            field=models.CharField(default='Non payé', max_length=20),
        ),
    ]
