# Generated by Django 3.2.9 on 2022-06-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0046_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mover',
            name='City',
        ),
    ]
