# Generated by Django 3.2.9 on 2022-06-06 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0049_mover_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mover_region',
            name='country',
        ),
        migrations.AddField(
            model_name='mover_region',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.region'),
        ),
    ]
