# Generated by Django 3.2.9 on 2022-06-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0050_auto_20220606_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request',
            name='City_Departure',
        ),
        migrations.AddField(
            model_name='quote_request',
            name='Region_Departure',
            field=models.CharField(default='', max_length=300),
        ),
    ]
