# Generated by Django 3.2.9 on 2022-06-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0051_auto_20220607_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request',
            name='Region_Departure',
        ),
        migrations.AddField(
            model_name='quote_request',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_app.region'),
        ),
    ]
