# Generated by Django 3.2.9 on 2022-06-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0052_auto_20220607_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request',
            name='City_Arrival',
        ),
        migrations.AddField(
            model_name='quote_request',
            name='City_Arrival_for_international_moving',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='quote_request',
            name='Region_Arrival_for_national_moving',
            field=models.CharField(default='', max_length=300),
        ),
    ]
