# Generated by Django 3.2.9 on 2022-06-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0053_auto_20220607_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request',
            name='email_sent_to_customer',
        ),
    ]
