# Generated by Django 3.2.9 on 2022-06-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0055_customers_notification_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers_notification_email',
            old_name='quote_request_distributed',
            new_name='moving_possibility',
        ),
        migrations.RemoveField(
            model_name='customers_notification_email',
            name='quote_request_not_distributed',
        ),
    ]
