# Generated by Django 3.2.9 on 2022-03-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0032_auto_20220302_1508'),
        ('user', '0002_delete_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movers_Password_Recovery_Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.mover')),
            ],
        ),
    ]
