# Generated by Django 3.2.9 on 2022-03-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220309_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=1.36, max_digits=5),
        ),
    ]
