# Generated by Django 3.2.9 on 2022-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_payment_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_request_payment',
            name='status',
            field=models.CharField(default='Non payé', max_length=30),
        ),
    ]
