# Generated by Django 3.2.9 on 2022-03-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_quote_request_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request_payment',
            name='status',
        ),
    ]
