# Generated by Django 3.2.9 on 2022-03-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_quote_request_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_request_payment',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='user/images/mover/payment/'),
        ),
    ]
