# Generated by Django 3.2.9 on 2022-03-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_quote_request_payment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request_payment',
            name='mover_quote_request',
        ),
        migrations.AddField(
            model_name='quote_request_payment',
            name='number_mover_quote_request_paid',
            field=models.IntegerField(default=0),
        ),
    ]
