# Generated by Django 3.2.9 on 2022-03-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_quote_request_payment_mover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_request_payment',
            name='number_mover_quote_request_paid',
        ),
    ]
