# Generated by Django 3.2.9 on 2022-03-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_quote_request_payment_number_mover_quote_request_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote_request_payment',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
