# Generated by Django 3.2.9 on 2022-03-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_quote_request_payment_validated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote_Request_Payment',
        ),
    ]
